/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 306775e0542b93b72d7bb155184e1e9d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database";
	}
	interface Env {
		ASSETS: Fetcher;
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		/** Set via `wrangler secret put SEED_SECRET` or Cloudflare dashboard */
		SEED_SECRET?: string;
	}
}
interface Env extends Cloudflare.Env {}
