/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 9ba3c3803522529b4424348020cdae24)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database" | "SyncedStateServer";
	}
	interface Env {
		ASSETS: Fetcher;
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		SYNCED_STATE_SERVER: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	}
}
interface Env extends Cloudflare.Env {}
